export const ListData = [
    {id: 1, nom: 'Ordinateur portable XYZ', description: "Un puissant ordinateur portable pour les professionnels.", prix:2000, categore: "Pc"},
    {id: 2, nom: "Souris sans fil ABC", description: "Une souris ergonomique avec technologie sans fil.", prix:150, categore: "Accessoires"},
    {id: 3, nom: "Écouteurs Bluetooth 123", description: "Écouteurs sans fil avec une qualité audio exceptionnelle.", prix:300, categore: "Audio"},
    {id: 4, nom: "Tablette XYZ", description: "Une tablette légère et compacte pour une utilisation quotidienne.", prix:1800, categore: "Tablette"},
    {id: 5, nom: "Imprimante Laser ABC", description: "Imprimante laser monochrome pour une impression rapide.", prix:700, categore: "Imprimantes"},
    {id: 6, nom: "Disque dur externe 1 To", description: "Stockez vos données en toute sécurité avec ce disque dur externe.", prix:400, categore: "Stockage"},
    {id: 7, nom: "Webcam HD 1080p", description: "Une webcam haute définition pour des visioconférences claires.", prix:300, categore: "Accessoires"},
    {id: 8, nom: "Routeur Wi-Fi 6", description: "Profitez d'une connexion Internet ultra-rapide avec ce routeur Wi-Fi 6.", prix:500, categore: 'Réseaux'},
    {id: 9, nom: 'Clavier mécanique RGB', description: 'Un clavier mécanique rétroéclairé avec des options de couleur RGB.', prix:250, categore: 'Accessoires'},
    {id: 10, nom: 'Logiciel de montage vidéo', description: 'Logiciel professionnel pour le montage vidéo avancé.', prix:600, categore: 'Logiciels'},
    {id: 11, nom: 'Enceinte Bluetooth ABC', description: 'Enceinte portable avec connectivité Bluetooth.', prix:120, categore: 'Audio'},
    {id: 12, nom: 'Écran tactile 15 pouces', description: 'Écran tactile pour une interaction plus intuitive.', prix:350, categore: 'Écrans'},
    {id: 13, nom: 'Scanner de documents XYZ', description: 'Scanner rapide et compact pour la numérisation de documents.', prix:180, categore: 'Accessoires'},
    {id: 14, nom: 'Étui pour ordinateur portable', description: 'Étui de protection pour ordinateur portable 15 pouces.', prix:40, categore: 'Accessoires'},
    {id: 15, nom: 'Souris ergonomique XYZ', description: 'Souris ergonomique conçue pour réduire la fatigue.', prix:80, categore: 'Accessoires'},
    {id: 16, nom: 'Carte mémoire 128 Go', description: 'Carte mémoire haute capacité pour le stockage supplémentaire.', prix:90, categore: 'Stockage'},
    {id: 17, nom: 'Stylet pour tablette', description: 'Stylet précis pour une utilisation facile sur les tablettes.', prix:30, categore: 'Accessoires'},
    {id: 18, nom: 'Adaptateur USB-C vers HDMI', description: 'Adaptateur pour connecter votre appareil USB-C à un écran HDMI.', prix:50, categore: 'Accessoires'},
    {id: 19, nom: 'Lampe de bureau LED', description: 'Lampe de bureau ajustable avec éclairage LED.', prix:60, categore: 'Accessoires'},
    {id: 20, nom: 'Étui de protection pour tablette', description: 'Étui robuste pour protéger votre tablette des chocs et des rayures.', prix:25, categore: 'Accessoires'},
    {id: 31, nom: 'Casque de jeu XYZ', description: 'Casque de jeu avec son surround et microphone antibruit.', prix:350, categore: 'Jeux'},
    {id: 32, nom: 'Batterie externe 20000mAh', description: 'Batterie externe puissante pour charger vos appareils en déplacement.', prix:120, categore: 'Batteries'},
    {id: 33, nom: 'Moniteur 27 pouces', description: 'Moniteur haute résolution pour une expérience visuelle immersive.', prix:800, categore: 'Écrans'},
];
